### ISSUE TITLE
11/19 Discussion (Paxos Made Live)

### ISSUE THREAD

**Issue by AKarbas** [lkuper/CSE232-2021-09#12]
Please add any missing scribes. :)

@SiegeEngine1
@Eirnf
@Eric-Vin
@euugenechou
@rahula00
@reeselevine
@Smruthi-Pobbathi
@AKarbas
@kevalnagda

My notes about the paper are available in [this doc](https://docs.google.com/document/d/1GNsVk4543wcZboH3mMKitz8dOCdNKnQ-IP5J9yHIRl8/). They need some restructuring and the addition of what was discussed in class (didn’t attend and haven’t watched it yet). Please make any changes you see fit, and I’ll do so as well.

Also, I propose using Google Docs’ “suggestions” mechanism for easier tracking of changes.

**Comment by kevalnagda** [comment]
Added comments from my notes.

**Comment by rahula00** [comment]
Added/edited responses for Q2 and Q3

**Comment by lkuper** [comment]
I just updated the wiki page for this one to the correct date, so just be aware if you're editing wiki pages via git that the name of the file has changed.  (So, pull first to pick up the rename.)

**Comment by euugenechou** [comment]
Hi all,

I've updated the doc with more fleshed-out summaries of the listed contributions.
If you have any issues with them, please edit them to your liking.
I'll merge in the finalized document to the wiki sometime close to midnight.

**Comment by EIRNf** [comment]
Added a few comments to Q3, felt it was a little unclear. 

Everything else looks great!

**Comment by AKarbas** [comment]
@lkuper Would you check and close the issue?

**Comment by lkuper** [comment]
Thanks, all.  Some feedback (mostly minor nitpicks):

* Nitpick on paper overview: I'd describe [Chubby](https://static.googleusercontent.com/media/research.google.com/en//archive/chubby-osdi06.pdf) as a *lock service* first, and only second as a file system.
* Q1: I think the paper is somewhat ambiguous on "master", and the in-class discussion reflected this somewhat.  Perhaps the ambiguity is due to the fact that in the paper there's a Chubby-level meaning for "master" (section 2) *and* a Paxos-level meaning for "master" (section 4.2), and these are different.  Actually, upon re-reading the paper, it's not clear to me which "master" is being referred to in the section on master leases (section 5.2).  Perhaps you all have a clearer idea of this than I do?
* Q2 nitpick: "the definition established in class in terms of a distributed system" isn't quite specific enough.  There are several definitions of "consistency" that *could* apply to distributed systems; that's the whole problem! :) Instead, I would say "consistency as in distributed data consistency models", which differentiates it from C in ACID, eventual consistency, consistency as in consistent hash functions, etc.
* Q3: Looks good!

**Comment by AKarbas** [comment]
@lkuper: Thanks for the comments. All were applied. Please check again.
