### ISSUE TITLE
12/3 Discussion --- MapReduce

### ISSUE THREAD

**Issue by philtcb** [lkuper/CSE232-2021-09#14]
Please add the missing scribes.
@SiegeEngine1 
@15siegela
@brianwzhao 
@nileshnegi 
@spacely 
@xuyanwen2012 
@AKarbas 
@aakash-mishra

**Comment by nileshnegi** [comment]
Added my notes to this [doc](https://docs.google.com/document/d/1AbQmm2ButYJNOKY5vXmqTtulqpA_tCBhZR0eSgetP0U/edit?usp=sharing)

**Comment by lkuper** [comment]
Hey folks -- how's it coming along?

**Comment by spacely** [comment]
Initial commit done based on the Google docs we are collaborating on. 
A final read through by someone. Anyone?

**Comment by 15siegela** [comment]
I'll take a look right now.
Thanks,
Alec Siegel

**Comment by AKarbas** [comment]
Did another pass over the doc and changed it in both places. I think it's ready @lkuper.

**Comment by SiegeEngine1** [comment]
I looked over the notes and it covers things discussed in my group quite well.

**Comment by lkuper** [comment]
Hi all -- thanks for the writeup!  Some feedback:

Paper overview nitpick: "Map and Reduce programming model" -> "MapReduce programming model"

Q1: Nitpick: I would just add that in the case of MapReduce, `N` is typically pretty big (on the order of tens or hundreds of thousands).  Also, re "they do not particularly care about redundancy" -- they do care about it; it's just that they opt for *redundant execution* (redoing the execution of a task when a worker fails) rather than redundant copies of data.  They make this point in a few places in the paper.

Q2 and Q3: these look great!

**Comment by AKarbas** [comment]
@lkuper: Done. Please verify.
