### ISSUE TITLE
10/18 Discussion

### ISSUE THREAD

**Issue by SiegeEngine1** [lkuper/CSE232-2021-09#5]
The following are the scribes for discussion 10/18: (Please add yourself or your group's scribe if the name is missing)
@15siegela 
@eimf
@Aditya-1996 
@NavikaG 
@nliittsc 
@spacely 
@Koda98
@das-17 

Also, as a trial, maybe the scribes could coordinate over a Google docs page instead of having multiple pushes be made to the master branch which require merging.

This is a google docs link with a blank format for the questions in the wiki:

https://docs.google.com/document/d/1uYFFx2FzPpbiK1oUwW-13ZxMG60Z8ExXNZsoWg5x3ZM/edit?usp=sharing

**Comment by AnirudhPotlapally** [comment]
Please add @Koda98 to the scribe list.

**Comment by das-17** [comment]
Do you guys wanna get on a Zoom call or something tomorrow evening to compile and finalize the answers to the questions?

**Comment by EIRNf** [comment]
Write up is mostly done! If you haven't read it please check it for anything missing or typos.

**Comment by lkuper** [comment]
Hi folks!  Thanks for the wiki writeup.  Q2 and Q3 look pretty good. Here is some feedback on the paper summary and on Q1.

### Summary

> The motivation established to do this is that of recording a stable property of a system. 

I think you meant to say *detecting* stable properties, not "recording".

> The details of the algorithm itself are left as an exercise to the reader.

This reads oddly; it sounds as if you're saying that the details are left out of the paper you're summarizing!  I think what you actually mean is that the details are left out of your summary (which is fine; it's supposed to be a summary, after all).  You don't need to say "left as an exercise to the reader".  I would just say "In summary, the algorithm works by..." and then have a two-or-three-sentence explanation.  Easier said than done, of course, but that's what a summary is.

### Q1

> If a process were to send a normal message and then a marker message to another process, and the marker marker arrived first, the second process would mark the incoming channel as empty before it received the message. In this case the snapshot would be inaccurate, because the first process would have recorded the message, and the second would not have. While not by definition an inconsistent snapshot, this scenarios results in a channel state recording being inaccurate and losing information of the workload.

I don't think this quite captures the essence of the problem.  The issue here is that there may be some invariant (e.g., "there is exactly one token in the system", as in the paper's extended example) that is true at all times while the system is executing, and so you want the invariant to also be true in the recorded snapshot.  A violation of FIFO delivery could mean that in-flight messages never get recorded in channel states, so if you have, for instance, a token in transit between processes, it might not appear in the snapshot at all.

> the integrity of the global snapshot is significantly compromised

> significantly impact the integrity of the global snapshot algorithm

What do you mean by "integrity"?  Also, once you say that the "integrity" of the *snapshot* is affected, and once you say that the integrity of the snapshot *algorithm* is affected.  These are different things; which is it?
