### ISSUE TITLE
11/5 Discussion

### ISSUE THREAD

**Issue by euugenechou** [lkuper/CSE232-2021-09#9]
List of scribes (may be missing some if manager hasn't updated the rolesheet):

- @SiegeEngine1 
- @Donnie-Stewart 
- @ekalvan 
- @Eric-Vin 
- @nileshnegi 
- @plredmond 
- @rahula00 
- @sukeswan 
- @kevalnagda 
- @AKarbas

**Comment by nileshnegi** [comment]
Added my notes to [https://docs.google.com/document/d/1dSu3dD31JJe2l3fdoSznrOocWNsuvUaJIvyRq5Ep2sU/edit?usp=sharing](https://docs.google.com/document/d/1dSu3dD31JJe2l3fdoSznrOocWNsuvUaJIvyRq5Ep2sU/edit?usp=sharing)

**Comment by Eric-Vin** [comment]
I made a few additions but overall looks great!

**Comment by rahula00** [comment]
I made a few additions to Q1 and Q3 as well. Looks good.

**Comment by kevalnagda** [comment]
Added a few points from my notes.

**Comment by sukeswan** [comment]
Made my edits!

**Comment by SiegeEngine1** [comment]
I made a few alterations and updated the wiki. 

I think we can close this issue now.

**Comment by AKarbas** [comment]
Sorry for the late response, all. I did some changes to the answers, and will add a paper summary soon.

**Comment by lkuper** [comment]
Hey folks! I'm about to look at this one and give feedback, but it looks like it's not quite finished?

**Comment by AKarbas** [comment]
Sorry about that. I’ll post the overview today.

Cheers,
Amin

**Comment by AKarbas** [comment]
Added the overview. Someone please double-check the overview and mention Lindsey after.

**Comment by Eric-Vin** [comment]
@AKarbas @lkuper Looked over it and it looks good!

**Comment by lkuper** [comment]
Hey folks!  Thanks for the writeup.  Some comments on Q1 and Q2:

## Q1

I don't understand the claim that splay replication gives you lower query latency.  It's the same number of messages for queries either way.  I'd argue instead that splay replication can improve overall throughput compared to p/b, just like chain replication does, but without the update latency disadvantage of chain replication.

## Q2

"Passive replication can be non-deterministic" is a bit vague.  I think what you mean to say here is in passive replication it's not a problem if the *computation* carried out on one replica is nondeterministic, but you need to explain *why* that is the case.

"active replication is the preferable choice when dealing with real time systems that require quick response even under the presence of faults or with systems that must handle byzantine faults" is a verbatim quote from the [source](https://jaksa.wordpress.com/2009/05/01/active-and-passive-replication-in-distributed-systems/) you found.  You can't do this -- if you're going to be using verbatim quotes, you need to put them in quotes.  Also, you shouldn't be using some random blog post as a source anyway (both because it's not good scholarship, and because all you really need to be doing here is summarizing the in-class discussion).

> Active replication (or State Machine Replication) is preferable if the state machine change is significant and communication bandwidth is scarce.

> Active Replication can be used in systems with low bandwidth but significant computation power in each process.

I think you're unnecessarily repeating yourself here.

**Comment by AKarbas** [comment]
Hey @lkuper,

Thanks for the in-depth look.

> ## Q1
> ...

Quoting from the chain-replication paper:
> the primary backup approach, where the primary, before responding to a query, must await acknowledgements from backups for prior updates.

We contrast this with splay replication, where the tail responds to reads from its local state. While the p/b requirement to await acks can be relaxed, this is what we meant by "lower query latency".
I added your note on throughput. And if you still think the "lower latency" argument is weak, we can remove it.


> ## Q2
> ...

Fixed.

Please check again.
